"""Generated bridges between tracks that will not beatmatch.

When two tracks are too far apart in tempo, forcing a match sags one of them.
A bridge solves it instead of hiding it: a rhythmic element that enters locked
to the outgoing track's tempo, travels to the incoming one's across a few
bars, and hands over locked. Both tracks then play at their own tempo.

The parts are synthesised rather than generated by a model. The whole value of
a bridge is sample-accurate control over where every beat lands and what tempo
it is travelling at, which is exactly what a generative model cannot be told.
A model could later supply the texture on top of this grid; the grid itself
has to be computed.
"""

import numpy as np

from audio_analysis.beat_key import _CAMELOT_MAJOR, _CAMELOT_MINOR, _PITCH_NAMES

_ROOT_OF_CAMELOT = {v: k for k, v in _CAMELOT_MAJOR.items()}
_ROOT_OF_CAMELOT.update({v: k for k, v in _CAMELOT_MINOR.items()})

# Per-preset pattern. Each entry is which sixteenths of a bar get a hit.
PATTERNS = {
    "house":    {"kick": [0, 4, 8, 12], "clap": [4, 12], "hat": [2, 6, 10, 14]},
    "festival": {"kick": [0, 4, 8, 12], "clap": [4, 12], "hat": [2, 6, 10, 14]},
    "afrobeat": {"kick": [0, 3, 6, 10], "clap": [4, 12], "hat": [2, 5, 8, 11, 14]},
    "hiphop":   {"kick": [0, 6, 10],    "clap": [4, 12], "hat": [0, 4, 8, 12]},
    "pop":      {"kick": [0, 4, 8, 12], "clap": [4, 12], "hat": [2, 6, 10, 14]},
}


def beat_times(tempo_from: float, tempo_to: float, beats: int) -> tuple[np.ndarray, float]:
    """Beat positions for a tempo ramping linearly in time.

    With tempo b(t) = t0 + (t1-t0)*t/T, the beat count is the integral of
    b/60, so beat k sits at the root of a quadratic. Solving it analytically
    keeps every hit exactly on the ramp rather than drifting.
    """
    t0, t1 = float(tempo_from), float(tempo_to)
    if t0 <= 0 or t1 <= 0:
        return np.zeros(beats), 0.0
    total = 120.0 * beats / (t0 + t1)

    k = np.arange(beats + 1, dtype=float)
    if abs(t1 - t0) < 1e-9:
        return k * 60.0 / t0, total
    a = (t1 - t0) / (2.0 * total)
    times = (-t0 + np.sqrt(t0 * t0 + 4.0 * a * 60.0 * k)) / (2.0 * a)
    return times, total


def make_bridge(tempo_from: float, tempo_to: float, bars: int, sr: int,
                preset: str = "pop", camelot: str | None = None,
                seed: int = 0) -> tuple[np.ndarray, np.ndarray, float]:
    """Build the bridge. Returns (stereo audio, beat times, duration)."""
    beats = max(4, bars * 4)
    times, duration = beat_times(tempo_from, tempo_to, beats)
    rng = np.random.default_rng(seed)

    n = int(np.ceil(duration * sr)) + sr // 2
    mono = np.zeros(n, dtype=np.float32)
    pattern = PATTERNS.get(preset, PATTERNS["pop"])

    def place(sig, at):
        i = int(at * sr)
        end = min(n, i + len(sig))
        if end > i:
            mono[i:end] += sig[: end - i]

    for bar in range(bars):
        base = bar * 4
        if base >= beats:
            break
        # Sixteenth grid inside this bar, following the ramp between beats.
        for step in range(16):
            beat_index = base + step // 4
            if beat_index + 1 >= len(times):
                break
            frac = (step % 4) / 4.0
            at = times[beat_index] + frac * (times[beat_index + 1] - times[beat_index])
            # Ramp intensity up so the bridge builds rather than sitting flat.
            drive = 0.55 + 0.45 * (bar / max(1, bars - 1))
            if step in pattern["kick"]:
                place(_kick(sr, 0.95 * drive), at)
            if step in pattern["clap"]:
                place(_clap(sr, rng, 0.45 * drive), at)
            if step in pattern["hat"]:
                place(_hat(sr, rng, 0.22 * drive), at)

    mono += _riser(n, sr, rng, duration)
    if camelot:
        mono += _drone(n, sr, camelot, duration)

    peak = float(np.max(np.abs(mono)))
    if peak > 0:
        mono = mono / peak * 0.7

    # Slight stereo spread so it does not sit dead centre against the tracks.
    left = mono.copy()
    right = mono.copy()
    offset = max(1, int(sr * 0.004))
    right[offset:] = mono[:-offset] * 0.97
    return np.vstack([left, right]).astype(np.float32), times, duration


def _kick(sr, level):
    t = np.arange(int(sr * 0.13)) / sr
    freq = 118.0 * np.exp(-t * 30.0) + 46.0
    return (level * np.exp(-t * 21.0) * np.sin(2 * np.pi * freq * t)).astype(np.float32)


def _clap(sr, rng, level):
    t = np.arange(int(sr * 0.16)) / sr
    body = np.exp(-t * 19.0) * rng.normal(0, 1, len(t))
    # A couple of pre-echoes are what make a clap read as a clap.
    out = body.copy()
    for delay, amp in ((0.006, 0.7), (0.012, 0.5)):
        d = int(delay * sr)
        out[d:] += body[:-d] * amp
    return (level * out * 0.4).astype(np.float32)


def _hat(sr, rng, level):
    t = np.arange(int(sr * 0.05)) / sr
    return (level * np.exp(-t * 95.0) * rng.normal(0, 1, len(t))).astype(np.float32)


def _riser(n, sr, rng, duration):
    """Rising filtered noise: the tension that makes a bridge feel deliberate."""
    t = np.arange(n) / sr
    progress = np.clip(t / max(duration, 1e-6), 0.0, 1.0)
    noise = rng.normal(0, 1, n)
    # Sweeping a one-pole highpass by mixing noise with its running mean.
    smoothed = np.convolve(noise, np.ones(64) / 64, mode="same")
    bright = noise - smoothed
    swept = smoothed * (1.0 - progress) + bright * progress
    envelope = (progress ** 2.2) * 0.16
    return (swept * envelope).astype(np.float32)


def _drone(n, sr, camelot, duration):
    """Low tonal bed on the incoming track's root, so the bridge leads into it."""
    root = _ROOT_OF_CAMELOT.get(camelot)
    if root is None:
        return np.zeros(n, dtype=np.float32)
    semitone = _PITCH_NAMES.index(root)
    freq = 55.0 * (2 ** (semitone / 12.0))

    t = np.arange(n) / sr
    progress = np.clip(t / max(duration, 1e-6), 0.0, 1.0)
    tone = (np.sin(2 * np.pi * freq * t)
            + 0.45 * np.sin(2 * np.pi * freq * 2 * t)
            + 0.2 * np.sin(2 * np.pi * freq * 3 * t))
    # Fade in, then duck away so it does not fight the incoming track.
    envelope = 0.14 * np.sin(np.pi * progress) ** 1.5
    return (tone * envelope).astype(np.float32)
